apiVersion: v1
kind: Pod
metadata:
  namespace: kube-system
  name: {{.Type}}-virtual-ip
spec:
  hostNetwork: true
  containers:
  - name: virtual-ip
    image: {{.VirtualIPImage}}
    command:
    - /virtual-ip
    - -id 
    - {{.ID}}
    - -bind 
    - {{.Bind}}
    - -peers 
    - {{.Peers}}
    - -interface 
    - {{.Interface}}
    - -virtual-ip 
    - {{.VirtualIP}}
    securityContext:
        privileged: true
