apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: monitoring
  name: prometheus-operator
  labels:
    app: prometheus-operator
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: prometheus-operator
  labels:
    app: prometheus-operator
rules:
- apiGroups:
  - extensions
  resources:
  - thirdpartyresources
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
- apiGroups:
  - monitoring.coreos.com
  resources:
  - alertmanager
  - alertmanagers
  - prometheus
  - prometheuses
  - service-monitor
  - servicemonitors
  - prometheusrules
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs: ["*"]
- apiGroups: [""]
  resources:
  - configmaps
  - secrets
  verbs: ["*"]
- apiGroups: [""]
  resources:
  - pods
  verbs: ["list", "delete"]
- apiGroups: [""]
  resources:
  - services
  - endpoints
  verbs: ["get", "create", "update"]
- apiGroups: [""]
  resources:
  - nodes
  verbs: ["list", "watch"]
- apiGroups: [""]
  resources:
  - namespaces
  verbs: ["list", "watch"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: psp-prometheus-operator
  labels:
    app: prometheus-operator
rules:
- apiGroups: ['extensions']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - prometheus-operator
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: prometheus-operator
  labels:
    app: prometheus-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-operator
subjects:
  - kind: ServiceAccount
    name: prometheus-operator
    namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: prometheus-operator
  name: psp-prometheus-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp-prometheus-operator
subjects:
  - kind: ServiceAccount
    namespace: monitoring
    name: prometheus-operator
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: monitoring
  name: prometheus-operator
  labels:
    app: prometheus-operator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus-operator
        operator: prometheus
    spec:
      containers:
        - name: prometheus-operator
          image: "{{.PrometheusOperatorImage}}"
          args:
            - --kubelet-service=kube-system/kubelet
            - --prometheus-config-reloader={{.PrometheusConfigReloaderImage}}
            - --config-reloader-image={{.ConfigMapReloadImage}}
          ports:
            - containerPort: 8080
              name: http
      serviceAccountName: prometheus-operator
---
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: prometheus-operator
  labels:
    app: prometheus-operator
spec:
  privileged: false
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
    - 'persistentVolumeClaim'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 0
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 0
        max: 65535
  readOnlyRootFilesystem: false
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-operator
  labels:
    app: prometheus-operator
    prometheus: prometheus-operator
spec:
  jobLabel: prometheus-operator
  selector:
    matchLabels:
      operated-prometheus: "true"
  namespaceSelector:
    matchNames:
      - "monitoring"
  endpoints:
  - port: http
    interval: 30s
    honorLabels: true
