---
apiVersion: v1
kind: Namespace
metadata:
  name: {{.Namespace}}

---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{.Namespace}}
  name: {{.SecretName}}
type: Opaque
data:
  # username = k8s-tew
  username: "azhzLXRldw=="
  password: "{{.Password}}"
