{{range $index, $node := .StorageControllers}}---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: storage
  name: ceph-mon-{{$node.Name}}
  labels:
    app: ceph-mon-{{$node.Name}}
spec:
  selector:
    matchLabels:
      app: ceph-mon-{{$node.Name}}
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ceph-mon-{{$node.Name}}
    spec:
      hostNetwork: true
      volumes:
      - name: ceph-config
        hostPath:
          path: {{$.CephConfigDirectory}}
          type: DirectoryOrCreate
      - name: ceph-data
        hostPath:
          path: {{$.CephDataDirectory}}
          type: DirectoryOrCreate
      nodeSelector:
        kubernetes.io/hostname: {{$node.Name}}
      tolerations:
        - effect: NoSchedule
          operator: Exists
      containers:
      - name: ceph-mon
        image: {{$.CephImage}}
        args: ["mon"]
        env:
        - name: MON_IP
          value: {{$node.IP}}
        - name: CEPH_PUBLIC_NETWORK
          value: {{$.PublicNetwork}}
        volumeMounts:
        - name: ceph-config
          mountPath: /etc/ceph
        - name: ceph-data
          mountPath: /var/lib/ceph
{{end}}{{range $index, $node := .StorageNodes}}---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: storage
  name: ceph-mds-{{$node.Name}}
  labels:
    app: ceph-mds-{{$node.Name}}
spec:
  selector:
    matchLabels:
      app: ceph-mds-{{$node.Name}}
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ceph-mds-{{$node.Name}}
    spec:
      hostNetwork: true
      volumes:
      - name: ceph-config
        hostPath:
          path: {{$.CephConfigDirectory}}
          type: DirectoryOrCreate
      - name: ceph-data
        hostPath:
          path: {{$.CephDataDirectory}}
          type: DirectoryOrCreate
      - name: ceph-dev
        hostPath:
          path: /dev
          type: DirectoryOrCreate
      nodeSelector:
        kubernetes.io/hostname: {{$node.Name}}
      tolerations:
        - effect: NoSchedule
          operator: Exists
      containers:
      - name: ceph-mds
        image: {{$.CephImage}}
        args: ["mds"]
        ports:
        - containerPort: 6800
        env:
        - name: CEPHFS_CREATE
          value: "1"
        - name: CEPHFS_DATA_POOL
          value: "{{$.CephFSPoolName}}"
        - name: CEPHFS_METADATA_POOL
          value: "{{$.CephFSPoolName}}_metadata"
        volumeMounts:
        - name: ceph-config
          mountPath: /etc/ceph
        - name: ceph-data
          mountPath: /var/lib/ceph
        - name: ceph-dev
          mountPath: /dev
        livenessProbe:
          tcpSocket:
            port: 6800
          initialDelaySeconds: 60
          timeoutSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 6800
          timeoutSeconds: 5
{{end}}{{range $index, $node := .StorageNodes}}---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: storage
  name: ceph-osd-{{$node.Name}}
  labels:
    app: ceph-osd-{{$node.Name}}
spec:
  selector:
    matchLabels:
      app: ceph-osd-{{$node.Name}}
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ceph-osd-{{$node.Name}}
    spec:
      hostNetwork: true
      volumes:
      - name: ceph-config
        hostPath:
          path: {{$.CephConfigDirectory}}
          type: DirectoryOrCreate
      - name: ceph-data
        hostPath:
          path: {{$.CephDataDirectory}}
          type: DirectoryOrCreate
      - name: ceph-dev
        hostPath:
          path: /dev
          type: DirectoryOrCreate
      nodeSelector:
        kubernetes.io/hostname: {{$node.Name}}
      tolerations:
        - effect: NoSchedule
          operator: Exists
      containers:
      - name: ceph-osd
        image: {{$.CephImage}}
        args: ["osd"]
        securityContext:
          privileged: true
        env:
        - name: OSD_TYPE
          value: directory
        volumeMounts:
        - name: ceph-config
          mountPath: /etc/ceph
        - name: ceph-data
          mountPath: /var/lib/ceph
        - name: ceph-dev
          mountPath: /dev
{{end}}---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: storage
  name: ceph-mgr
  labels:
    app: ceph-mgr
spec:
  selector:
    matchLabels:
      app: ceph-mgr
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ceph-mgr
    spec:
      tolerations:
        - effect: NoSchedule
          operator: Exists
      nodeSelector:
        node-role.kubernetes.io/storage: "true"
      hostNetwork: true
      volumes:
      - name: ceph-config
        hostPath:
          path: {{$.CephConfigDirectory}}
          type: DirectoryOrCreate
      - name: ceph-data
        hostPath:
          path: {{$.CephDataDirectory}}
          type: DirectoryOrCreate
      containers:
      - name: ceph-mgr
        image: {{$.CephImage}}
        securityContext:
          privileged: true
        args: ["mgr"]
        volumeMounts:
        - name: ceph-config
          mountPath: /etc/ceph
        - name: ceph-data
          mountPath: /var/lib/ceph
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: storage
  name: ceph-rgw
  labels:
    app: ceph-rgw
spec:
  selector:
    matchLabels:
      app: ceph-rgw
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ceph-rgw
    spec:
      tolerations:
        - effect: NoSchedule
          operator: Exists
      nodeSelector:
        node-role.kubernetes.io/storage: "true"
      volumes:
      - name: ceph-config
        hostPath:
          path: {{$.CephConfigDirectory}}
          type: DirectoryOrCreate
      - name: ceph-data
        hostPath:
          path: {{$.CephDataDirectory}}
          type: DirectoryOrCreate
      containers:
      - name: ceph-rgw
        image: {{$.CephImage}}
        args: ["rgw"]
        ports:
        - containerPort: 7480
          name: rgw
        volumeMounts:
        - name: ceph-config
          mountPath: /etc/ceph
        - name: ceph-data
          mountPath: /var/lib/ceph
        livenessProbe:
          tcpSocket:
            port: 7480
          initialDelaySeconds: 60
          timeoutSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 7480
          timeoutSeconds: 5
---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: storage
  name: ceph-setup
spec:
  template:
    metadata:
      name: ceph-setup
    spec:
      tolerations:
        - effect: NoSchedule
          operator: Exists
      nodeSelector:
        node-role.kubernetes.io/storage: "true"
      restartPolicy: OnFailure
      volumes:
      - name: ceph-config
        hostPath:
          path: {{$.CephConfigDirectory}}
          type: DirectoryOrCreate
      - name: ceph-data
        hostPath:
          path: {{$.CephDataDirectory}}
          type: DirectoryOrCreate
      containers:
      - name: ceph
        image: {{$.CephImage}}
        command:
        - /bin/sh
        - -c
        - "ceph mgr module enable dashboard && ceph dashboard create-self-signed-cert && ceph dashboard set-login-credentials admin changeme && ceph mgr module disable dashboard && ceph mgr module enable dashboard && ceph osd pool create {{.CephRBDPoolName}} 256 256 && ceph osd pool application enable {{.CephRBDPoolName}} rbd"
        volumeMounts:
        - name: ceph-config
          mountPath: /etc/ceph
        - name: ceph-data
          mountPath: /var/lib/ceph
---
apiVersion: v1
kind: Service
metadata:
    namespace: storage
    name: ceph-rgw
    labels:
        app: ceph-rgw
spec:
    type: NodePort
    ports:
    - port: 7480
      protocol: TCP
      nodePort: {{.CephRadosGatewayPort}}
    selector:
      app: ceph-rgw
---
apiVersion: v1
kind: Service
metadata:
    namespace: storage
    name: ceph-mgr
    labels:
        app: ceph-mgr
spec:
    type: NodePort
    ports:
    - port: 8443
      protocol: TCP
      nodePort: {{.CephManagerPort}}
    selector:
      app: ceph-mgr
