apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: storage
  name: rbd-provisioner
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rbd-provisioner
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["services"]
    resourceNames: ["kube-dns", "coredns"]
    verbs: ["list", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: storage
  name: rbd-provisioner
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rbd-provisioner
subjects:
  - kind: ServiceAccount
    name: rbd-provisioner
    namespace: storage
roleRef:
  kind: ClusterRole
  name: rbd-provisioner
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rbd-provisioner
  namespace: storage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rbd-provisioner
subjects:
- kind: ServiceAccount
  name: rbd-provisioner
  namespace: storage
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ceph
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: ceph.com/rbd
parameters:
  monitors: {{range $index, $node := .StorageControllers}}{{if $index}},{{end}}{{$node.IP}}:6789{{end}}
  pool: {{.CephRBDPoolName}}
  adminId: admin
  adminSecretName: ceph-admin
  adminSecretNamespace: storage
  userId: k8s-tew
  userSecretName: ceph-k8s-tew
  userSecretNamespace: storage
  imageFormat: "2"
  imageFeatures: layering
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: storage
  name: rbd-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rbd-provisioner
    spec:
      containers:
      - name: rbd-provisioner
        image: "{{$.RBDProvisionerImage}}"
        env:
        - name: PROVISIONER_NAME
          value: ceph.com/rbd
      serviceAccount: rbd-provisioner
{{range $index, $node := .StorageControllers}}---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: storage
  name: ceph-mon-{{$node.Name}}
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ceph-mon-{{$node.Name}}
    spec:
      hostNetwork: true
      volumes:
      - name: ceph-config
        hostPath:
          path: {{$.CephConfigDirectory}}
          type: DirectoryOrCreate
      - name: ceph-data
        hostPath:
          path: {{$.CephDataDirectory}}
          type: DirectoryOrCreate
      nodeSelector:
        kubernetes.io/hostname: {{$node.Name}}
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
      containers:
      - name: ceph-mon
        image: {{$.CephImage}}
        args: ["mon"]
        env:
        - name: MON_IP
          value: {{$node.IP}}
        - name: CEPH_PUBLIC_NETWORK
          value: {{$.PublicNetwork}}
        volumeMounts:
        - name: ceph-config
          mountPath: /etc/ceph
        - name: ceph-data
          mountPath: /var/lib/ceph
{{end}}{{range $index, $node := .StorageNodes}}---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: storage
  name: ceph-mds-{{$node.Name}}
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ceph-mds-{{$node.Name}}
    spec:
      hostNetwork: true
      volumes:
      - name: ceph-config
        hostPath:
          path: {{$.CephConfigDirectory}}
          type: DirectoryOrCreate
      - name: ceph-data
        hostPath:
          path: {{$.CephDataDirectory}}
          type: DirectoryOrCreate
      - name: ceph-dev
        hostPath:
          path: /dev
          type: DirectoryOrCreate
      nodeSelector:
        kubernetes.io/hostname: {{$node.Name}}
      tolerations:
        - effect: NoExecute
          operator: Exists
      containers:
      - name: ceph-mds
        image: {{$.CephImage}}
        args: ["mds"]
        ports:
        - containerPort: 6800
        env:
        - name: CEPHFS_CREATE
          value: "1"
        - name: CEPHFS_DATA_POOL
          value: "{{$.CephFSPoolName}}"
        - name: CEPHFS_METADATA_POOL
          value: "{{$.CephFSPoolName}}_metadata"
        volumeMounts:
        - name: ceph-config
          mountPath: /etc/ceph
        - name: ceph-data
          mountPath: /var/lib/ceph
        - name: ceph-dev
          mountPath: /dev
        livenessProbe:
          tcpSocket:
            port: 6800
          initialDelaySeconds: 60
          timeoutSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 6800
          timeoutSeconds: 5
{{end}}{{range $index, $node := .StorageNodes}}---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: storage
  name: ceph-osd-{{$node.Name}}
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ceph-osd-{{$node.Name}}
    spec:
      hostNetwork: true
      volumes:
      - name: ceph-config
        hostPath:
          path: {{$.CephConfigDirectory}}
          type: DirectoryOrCreate
      - name: ceph-data
        hostPath:
          path: {{$.CephDataDirectory}}
          type: DirectoryOrCreate
      - name: ceph-dev
        hostPath:
          path: /dev
          type: DirectoryOrCreate
      nodeSelector:
        kubernetes.io/hostname: {{$node.Name}}
      tolerations:
        - effect: NoExecute
          operator: Exists
      containers:
      - name: ceph-osd
        image: {{$.CephImage}}
        args: ["osd"]
        securityContext:
          privileged: true
        env:
        - name: OSD_TYPE
          value: directory
        volumeMounts:
        - name: ceph-config
          mountPath: /etc/ceph
        - name: ceph-data
          mountPath: /var/lib/ceph
        - name: ceph-dev
          mountPath: /dev
{{end}}---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: storage
  name: ceph-mgr
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ceph-mgr
    spec:
      hostNetwork: true
      volumes:
      - name: ceph-config
        hostPath:
          path: {{$.CephConfigDirectory}}
          type: DirectoryOrCreate
      - name: ceph-data
        hostPath:
          path: {{$.CephDataDirectory}}
          type: DirectoryOrCreate
      containers:
      - name: ceph-mgr
        image: {{$.CephImage}}
        securityContext:
          privileged: true
        args: ["mgr"]
        volumeMounts:
        - name: ceph-config
          mountPath: /etc/ceph
        - name: ceph-data
          mountPath: /var/lib/ceph
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: storage
  name: ceph-rgw
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ceph-rgw
    spec:
      volumes:
      - name: ceph-config
        hostPath:
          path: {{$.CephConfigDirectory}}
          type: DirectoryOrCreate
      - name: ceph-data
        hostPath:
          path: {{$.CephDataDirectory}}
          type: DirectoryOrCreate
      containers:
      - name: ceph-mgr
        image: {{$.CephImage}}
        args: ["rgw"]
        ports:
        - containerPort: 8080
          name: rgw
        volumeMounts:
        - name: ceph-config
          mountPath: /etc/ceph
        - name: ceph-data
          mountPath: /var/lib/ceph
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 8080
          timeoutSeconds: 5
---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: storage
  name: ceph-setup
spec:
  template:
    metadata:
      name: ceph-setup
    spec:
      restartPolicy: OnFailure
      volumes:
      - name: ceph-config
        hostPath:
          path: {{$.CephConfigDirectory}}
          type: DirectoryOrCreate
      - name: ceph-data
        hostPath:
          path: {{$.CephDataDirectory}}
          type: DirectoryOrCreate
      containers:
      - name: ceph
        image: {{$.CephImage}}
        command:
        - /bin/sh
        - -c
        - "ceph mgr module enable dashboard && ceph dashboard create-self-signed-cert && ceph config set mgr mgr/dashboard/server_port 7000 && ceph dashboard set-login-credentials admin changeme && ceph mgr module disable dashboard && ceph mgr module enable dashboard && ceph osd pool create {{.CephRBDPoolName}} 256 256 && ceph osd pool application enable {{.CephRBDPoolName}} rbd"
        volumeMounts:
        - name: ceph-config
          mountPath: /etc/ceph
        - name: ceph-data
          mountPath: /var/lib/ceph
---
apiVersion: v1
kind: Service
metadata:
    namespace: storage
    name: ceph-rgw
    labels:
        app: ceph
        daemon: rgw
spec:
    type: NodePort
    ports:
    - port: 8080
      protocol: TCP
      nodePort: 30808
    selector:
      app: ceph
      daemon: rgw
