apiVersion: v1
kind: Namespace
metadata:
  name: storage

---
apiVersion: v1
kind: Secret
metadata:
    name: ceph-admin
    namespace: storage
type: "kubernetes.io/rbd"
data:
    key: {{.ClientAdminKey | base64}}

---
apiVersion: v1
kind: Secret
metadata:
    name: ceph-k8s-tew
    namespace: storage
type: "kubernetes.io/rbd"
data:
    key: {{.ClientK8STEWKey | base64}}

---
apiVersion: v1
kind: Secret
metadata:
    name: csi-rbd-secret
    namespace: storage
data:
    adminID: {{"admin" | base64}}
    adminKey: {{.ClientAdminKey | base64}}
    userID: {{"k8s-tew" | base64}}
    userKey: {{.ClientK8STEWKey | base64}}

---
apiVersion: v1
kind: Secret
metadata:
    name: csi-cephfs-secret
    namespace: storage
data:
    adminID: {{"admin" | base64}}
    adminKey: {{.ClientAdminKey | base64}}

